/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author HP
 */
import Entidad.*;
import Negocios.*;
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class FrmCargo extends javax.swing.JFrame {

    /**
     * Creates new form FrmCargo
     */
    public FrmCargo() {
        initComponents();
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCargo = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mantenimiento de Cargo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        tblCargo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "GUARDAR", "EDITAR", "ELIMINAR", "BUSCAR", "LISTAR"
            }
        ));
        jScrollPane1.setViewportView(tblCargo);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnReturn.setText("Regresar al menú");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReturn)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnReturn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    boolean searchAlertShown = false;
    private void listar() {
       clsNcargo objNC = new clsNcargo();
        // Assuming MtdListarCargo returns a List or array of cargo objects
        List<clsECargo> listaCargos = objNC.MtdListarCargo();

        DefaultTableModel model = (DefaultTableModel) tblCargo.getModel();
        model.setRowCount(0);

        for (clsECargo cargo : listaCargos) {
            Object[] row = {cargo.getCodigo(), cargo.getNombre(), "GUARDAR", "EDITAR", "ELIMINAR","BUSCAR","LISTAR"};
            model.addRow(row);
        }
        tblCargo.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int row = tblCargo.rowAtPoint(evt.getPoint());
            int col = tblCargo.columnAtPoint(evt.getPoint());
            // Si se hace clic en el botón "GUARDAR"
            if (col == 2) {
                // Obtener el modelo de la tabla
                DefaultTableModel model = (DefaultTableModel) tblCargo.getModel();

                // Obtener la última fila (la que acabamos de agregar o editar)
                int lastRow = model.getRowCount() - 1;

                // Obtener los datos de la última fila
                int codigo = Integer.parseInt(model.getValueAt(lastRow, 0).toString());
                String nombre = model.getValueAt(lastRow, 1).toString();

                // Crear un objeto clsECargo con los datos obtenidos
                clsECargo nuevoCargo = new clsECargo();
                nuevoCargo.setCodigo(codigo);
                nuevoCargo.setNombre(nombre);

                // Guardar el nuevo cargo en la base de datos
                clsNcargo objNC = new clsNcargo();
                if (objNC.MtdGuardarCargo(nuevoCargo)) {
                    listar();
                } 
            }
            // Si se hace clic en el botón "EDITAR"
            if (col == 3) {
                // Obtener el modelo de la tabla
                DefaultTableModel model = (DefaultTableModel) tblCargo.getModel();

                // Obtener la última fila (la que acabamos de agregar o editar)
                int lastRow = model.getRowCount() - 1;

                // Obtener los datos de la última fila
                int codigo = Integer.parseInt(model.getValueAt(lastRow, 0).toString());
                String nombre = model.getValueAt(lastRow, 1).toString();

                // Crear un objeto clsECargo con los datos obtenidos
                clsECargo nuevoCargo = new clsECargo();
                nuevoCargo.setCodigo(codigo);
                nuevoCargo.setNombre(nombre);

                // Guardar el nuevo cargo en la base de datos
                clsNcargo objNC = new clsNcargo();
                if (objNC.MtdModificarCargo(nuevoCargo)) {
                    listar();
                } 
            }

            // Si se hace clic en el botón "ELIMINAR"
            if (col == 4) {
                clsECargo objEC = new clsECargo();
                clsNcargo objNC = new clsNcargo();
                objEC.setCodigo(Integer.parseInt(model.getValueAt(row, 0).toString()));
                if (objNC.MtdEliminarCargo(objEC)) {
                    listar();
                } 
            }
            if (col == 5) {
                clsNcargo objNC = new clsNcargo();
                String codigoNombre = JOptionPane.showInputDialog("Ingrese el código o nombre a buscar");

                // Assuming MtdBuscarCargo returns a List or array of cargo objects
                List<clsECargo> listaCargos = objNC.MtdBuscarCargo(codigoNombre);

                DefaultTableModel model = (DefaultTableModel) tblCargo.getModel();
                model.setRowCount(0);

                for (clsECargo cargo : listaCargos) {
                    Object[] row1 = {cargo.getCodigo(), cargo.getNombre(), "GUARDAR", "EDITAR", "ELIMINAR", "BUSCAR", "LISTAR"};
                    model.addRow(row1);
                }

                // Set the flag to true after showing the alert
                searchAlertShown = true;

                // Reset the flag in a short delay (you may adjust the delay based on your needs)
                Timer timer = new Timer(1000, e -> searchAlertShown = false);
                timer.setRepeats(false);
                timer.start();
            }
            if (col == 6) {
                listar();
            }
        }
    }); 
    }    
    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        FrmPrincipal frmPrincipal = new FrmPrincipal();
        frmPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblCargo.getModel();
        // Agregar una nueva fila vacía
        model.addRow(new Object[]{null, null, "GUARDAR", "EDITAR", "ELIMINAR","BUSCAR","LISTAR"});

        // Obtener la última fila (la que acabamos de agregar)
        int lastRow = model.getRowCount() - 1;

        // Enfocar y empezar la edición en la celda de código (columna 0)
        tblCargo.requestFocus();
        tblCargo.editCellAt(lastRow, 0);
    }//GEN-LAST:event_btnNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCargo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCargo;
    // End of variables declaration//GEN-END:variables
}
